config/routes.rb
Rails.application.routes.draw do

	devise_for :managers, controllers: {
			sessions: 'managers/sessions',
			passwords: 'managers/passwords',
			registrations: 'managers/registrations',
			invitations: 'managers/invitations'
	}

	devise_scope :user do
		authenticated :user do
			root :to => 'users/stamp_card#index', as: :user_authenticated_root
		end
		unauthenticated :user do
			root :to => 'users/sessions#new', as: :user_unauthenticated_root
		end
	end

	devise_for :users, controllers: {
			sessions: 'users/sessions',
			passwords: 'users/passwords',
			registrations: 'users/registrations',
			confirmations: 'users/confirmations'
	}

	namespace :managers do
		get '/', to: 'index#index'
		resources :stamp_cards
		resources :users, :only => [:index, :show]
		resources :managers, :only => [:index, :show, :destroy]
	end

	namespace :users do
		get 'stamp_cards', to: 'stamp_card#index'
		get 'stamp_card/:stamp_card_id', to: 'stamp_card#detail', as: 'stamp_card'
		get 'stamp_card/:stamp_card_id/my_stamps', to: 'stamp_card#my_stamps', as: 'stamp_card_my_stamps'
		post 'stamp_card/stamp', to: 'stamp_card#stamp', as: 'stamp_card_stamp'
	end
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/managers/base_controller.rb
class Managers::BaseController < ApplicationController
	layout 'managers/application'

	before_action :authenticate_manager!

end

app/controllers/managers/index_controller.rb
class Managers::IndexController < Managers::BaseController

	def index

	end
end

app/controllers/managers/invitations_controller.rb
class Managers::InvitationsController < Devise::InvitationsController
	layout :resolve_layout

	def after_invite_path_for(inviter, invitee)
		managers_path
	end

	def after_accept_path_for(resource)
		managers_path
	end

	private

	def resolve_layout
		if action_name == 'new' || action_name == 'create'
			'managers/application'
		else
			'managers/login'
		end
	end
end

app/controllers/managers/managers_controller.rb
class Managers::ManagersController < Managers::BaseController
  before_action :set_manager, only: [:show, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all.order(:id)
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_managers_url, notice: '管理者を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.fetch(:manager, {})
    end
end

app/controllers/managers/passwords_controller.rb
# frozen_string_literal: true

class Managers::PasswordsController < Devise::PasswordsController
	layout 'managers/login'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/managers/registrations_controller.rb
# frozen_string_literal: true

class Managers::RegistrationsController < Devise::RegistrationsController
	layout :resolve_layout

	before_action :guard_signup!, only: %i[cancel new create]

	# before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def after_update_path_for(resource)
		managers_path
  end

	private

	def guard_signup!
		raise ActionController::RoutingError, 'NOT FOUND'
	end

	def resolve_layout
		if action_name == 'new' || action_name == 'create'
			'managers/login'
		else
			'managers/application'
		end
	end
end

app/controllers/managers/sessions_controller.rb
# frozen_string_literal: true

class Managers::SessionsController < Devise::SessionsController
	layout 'managers/login'
	# before_action :configure_sign_in_params, only: [:create]

	# GET /resource/sign_in
	# def new
	#   super
	# end

	# POST /resource/sign_in
	# def create
	#   super
	# end

	# DELETE /resource/sign_out
	# def destroy
	#   super
	# end

	# protected

	# If you have extra params to permit, append them to the sanitizer.
	# def configure_sign_in_params
	#   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
	# end

	def after_sign_in_path_for(resource)
		managers_path
	end

	def after_sign_out_path_for(resource)
		new_manager_session_path
	end
end

app/controllers/managers/stamp_cards_controller.rb
class Managers::StampCardsController < Managers::BaseController
	before_action :set_stamp_card, only: [:show, :edit, :update, :destroy]

	# GET /stamp_cards
	# GET /stamp_cards.json
	def index
		@stamp_cards = StampCard.all.order(id: :desc)
	end

	# GET /stamp_cards/1
	# GET /stamp_cards/1.json
	def show
	end

	# GET /stamp_cards/new
	def new
		@stamp_card = StampCard.new
	end

	# GET /stamp_cards/1/edit
	def edit
	end

	# POST /stamp_cards
	# POST /stamp_cards.json
	def create
		@stamp_card = StampCard.new(stamp_card_params)

		respond_to do |format|
			if @stamp_card.save
				format.html {redirect_to managers_stamp_cards_path, notice: 'スタンプカードを作成しました。'}
			else
				format.html {render :new}
			end
		end
	end

	# PATCH/PUT /stamp_cards/1
	# PATCH/PUT /stamp_cards/1.json
	def update
		respond_to do |format|
			if @stamp_card.update(stamp_card_params)
				format.html {redirect_to managers_stamp_cards_path, notice: 'スタンプカードを更新しました。'}
				format.json {render :show, status: :ok, location: @stamp_card}
			else
				format.html {render :edit}
				format.json {render json: @stamp_card.errors, status: :unprocessable_entity}
			end
		end
	end

	# DELETE /stamp_cards/1
	# DELETE /stamp_cards/1.json
	def destroy
		@stamp_card.destroy
		respond_to do |format|
			format.html {redirect_to managers_stamp_cards_url, notice: 'スタンプカードを削除しました。'}
			format.json {head :no_content}
		end
	end

	private

	# Use callbacks to share common setup or constraints between actions.
	def set_stamp_card
		@stamp_card = StampCard.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def stamp_card_params
		params.require(:stamp_card).permit(:name, :count, :description, :start_at, :end_at)
	end
end

app/controllers/managers/users_controller.rb
class Managers::UsersController < Managers::BaseController
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/managers/managers_helper.rb
module Managers::ManagersHelper
end

app/helpers/managers/stamp_cards_helper.rb
module Managers::StampCardsHelper
end

app/helpers/managers/users_helper.rb
module Managers::UsersHelper
end

app/views/layouts/managers/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SOL STAMP - 管理画面</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_pack_tag 'application-manager', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application-manager', 'data-turbolinks-track': 'reload' %>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<body class="managerWrapper">
<aside class="sidemenu">
	<h1><%= link_to "SOL STAMP 管理画面", managers_path %></h1>
	<div id="nav-drawer">
		<input id="nav-input" type="checkbox" class="nav-unshown">
		<label id="nav-open" for="nav-input"><span></span></label>
		<label class="nav-unshown nav-close-bg" for="nav-input"></label>
		<nav id="nav-content">
			<label class="nav-close" for="nav-input">×</label>
			<ul>
				<li>スタンプカード
					<ul>
						<li><%= link_to 'スタンプカード一覧', managers_stamp_cards_path %></li>
						<li><%= link_to 'スタンプカード作成', new_managers_stamp_card_path %></li>
						<li>てしごと部カード</li>
					</ul>
				</li>
				<li>ユーザ管理
					<ul>
						<li><%= link_to 'ユーザ一覧', managers_users_path %></li>
						<li><%= link_to '管理者一覧', managers_managers_path %></li>
						<li><%= link_to 'アカウント編集', edit_manager_registration_path %></li>
						<li><%= link_to '管理者を招待する', new_manager_invitation_path %></li>
					</ul>
				</li>
			</ul>
			<%= link_to 'ログアウト', destroy_manager_session_path, method: :delete, class: 'cmn-btn mgt-30' %>
		</nav>
	</div>
</aside>
<main class="main">
	<div class="container">
		<%- if notice.present? %>
			<p class="cmn-notice"><%= notice %></p>
		<%- end %>
		<%- if alert.present? %>
			<p class="cmn-alert"><%= alert %></p>
		<%- end %>
		<%= yield %>
	</div>
</main>
</body>
</html>

app/views/layouts/managers/login.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SOL STAMP - 管理画面</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_pack_tag 'application-manager', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application-manager', 'data-turbolinks-track': 'reload' %>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<body>
<header class="header">
	<h1><%= link_to "SOL STAMP 管理画面", new_manager_session_path %></h1>
</header>
<div class="container is-short">
	<%- if notice.present? %>
		<p class="cmn-notice"><%= notice %></p>
	<%- end %>
	<%- if alert.present? %>
		<p class="cmn-alert"><%= alert %></p>
	<%- end %>
	<%= yield %>
</div>
</body>
</html>