config/routes.rb
Rails.application.routes.draw do

	devise_for :managers, controllers: {
			sessions: 'managers/sessions',
			passwords: 'managers/passwords',
			registrations: 'managers/registrations',
			invitations: 'managers/invitations'
	}

	devise_scope :user do
		authenticated :user do
			root :to => 'users/stamp_card#index', as: :user_authenticated_root
		end
		unauthenticated :user do
			root :to => 'users/sessions#new', as: :user_unauthenticated_root
		end
	end

	devise_for :users, controllers: {
			sessions: 'users/sessions',
			passwords: 'users/passwords',
			registrations: 'users/registrations',
			confirmations: 'users/confirmations'
	}

	namespace :managers do
		get '/', to: 'index#index'
		resources :stamp_cards
		resources :users, :only => [:index, :show]
		resources :managers, :only => [:index, :show, :destroy]
	end

	namespace :users do
		get 'stamp_cards', to: 'stamp_card#index'
		get 'stamp_card/:stamp_card_id', to: 'stamp_card#detail', as: 'stamp_card'
		get 'stamp_card/:stamp_card_id/my_stamps', to: 'stamp_card#my_stamps', as: 'stamp_card_my_stamps'
		post 'stamp_card/stamp', to: 'stamp_card#stamp', as: 'stamp_card_stamp'
	end
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/stamp_card.rb
class StampCard < ApplicationRecord
	has_many :stamps

	validates :name, presence: true
	validates :count, presence: true, numericality: { only_integer: true }
	validates :description, presence: true
	validates :start_at, presence: true
	validates :end_at, presence: true

	validates_date :start_at, allow_blank: true
	validates_date :end_at, allow_blank: true

	def self.active_cards
		self.where('start_at <= ?', Time.zone.now.to_date).where('? <= end_at', Time.zone.now.to_date)
	end

	def self.old_cards
		self.where('end_at < ?', Time.zone.now.to_date)
	end

	def active?
		self.start_at <= Time.zone.today && Time.zone.today <= self.end_at
	end

	def complete?(user_id)
		self.count <= got_stamps(user_id).count
	end

	def got_stamps(user_id)
		self.stamps.where(user_id: user_id)
	end

end

app/controllers/managers/base_controller.rb
class Managers::BaseController < ApplicationController
	layout 'managers/application'

	before_action :authenticate_manager!

end

app/controllers/managers/index_controller.rb
class Managers::IndexController < Managers::BaseController

	def index

	end
end

app/controllers/managers/invitations_controller.rb
class Managers::InvitationsController < Devise::InvitationsController
	layout :resolve_layout

	def after_invite_path_for(inviter, invitee)
		managers_path
	end

	def after_accept_path_for(resource)
		managers_path
	end

	private

	def resolve_layout
		if action_name == 'new' || action_name == 'create'
			'managers/application'
		else
			'managers/login'
		end
	end
end

app/controllers/managers/managers_controller.rb
class Managers::ManagersController < Managers::BaseController
  before_action :set_manager, only: [:show, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all.order(:id)
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_managers_url, notice: '管理者を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.fetch(:manager, {})
    end
end

app/controllers/managers/passwords_controller.rb
# frozen_string_literal: true

class Managers::PasswordsController < Devise::PasswordsController
	layout 'managers/login'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/managers/registrations_controller.rb
# frozen_string_literal: true

class Managers::RegistrationsController < Devise::RegistrationsController
	layout :resolve_layout

	before_action :guard_signup!, only: %i[cancel new create]

	# before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def after_update_path_for(resource)
		managers_path
  end

	private

	def guard_signup!
		raise ActionController::RoutingError, 'NOT FOUND'
	end

	def resolve_layout
		if action_name == 'new' || action_name == 'create'
			'managers/login'
		else
			'managers/application'
		end
	end
end

app/controllers/managers/sessions_controller.rb
# frozen_string_literal: true

class Managers::SessionsController < Devise::SessionsController
	layout 'managers/login'
	# before_action :configure_sign_in_params, only: [:create]

	# GET /resource/sign_in
	# def new
	#   super
	# end

	# POST /resource/sign_in
	# def create
	#   super
	# end

	# DELETE /resource/sign_out
	# def destroy
	#   super
	# end

	# protected

	# If you have extra params to permit, append them to the sanitizer.
	# def configure_sign_in_params
	#   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
	# end

	def after_sign_in_path_for(resource)
		managers_path
	end

	def after_sign_out_path_for(resource)
		new_manager_session_path
	end
end

app/controllers/managers/stamp_cards_controller.rb
class Managers::StampCardsController < Managers::BaseController
	before_action :set_stamp_card, only: [:show, :edit, :update, :destroy]

	# GET /stamp_cards
	# GET /stamp_cards.json
	def index
		@stamp_cards = StampCard.all.order(id: :desc)
	end

	# GET /stamp_cards/1
	# GET /stamp_cards/1.json
	def show
	end

	# GET /stamp_cards/new
	def new
		@stamp_card = StampCard.new
	end

	# GET /stamp_cards/1/edit
	def edit
	end

	# POST /stamp_cards
	# POST /stamp_cards.json
	def create
		@stamp_card = StampCard.new(stamp_card_params)

		respond_to do |format|
			if @stamp_card.save
				format.html {redirect_to managers_stamp_cards_path, notice: 'スタンプカードを作成しました。'}
			else
				format.html {render :new}
			end
		end
	end

	# PATCH/PUT /stamp_cards/1
	# PATCH/PUT /stamp_cards/1.json
	def update
		respond_to do |format|
			if @stamp_card.update(stamp_card_params)
				format.html {redirect_to managers_stamp_cards_path, notice: 'スタンプカードを更新しました。'}
				format.json {render :show, status: :ok, location: @stamp_card}
			else
				format.html {render :edit}
				format.json {render json: @stamp_card.errors, status: :unprocessable_entity}
			end
		end
	end

	# DELETE /stamp_cards/1
	# DELETE /stamp_cards/1.json
	def destroy
		@stamp_card.destroy
		respond_to do |format|
			format.html {redirect_to managers_stamp_cards_url, notice: 'スタンプカードを削除しました。'}
			format.json {head :no_content}
		end
	end

	private

	# Use callbacks to share common setup or constraints between actions.
	def set_stamp_card
		@stamp_card = StampCard.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def stamp_card_params
		params.require(:stamp_card).permit(:name, :count, :description, :start_at, :end_at)
	end
end

app/controllers/managers/users_controller.rb
class Managers::UsersController < Managers::BaseController
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/controllers/users/stamp_card_controller.rb
class Users::StampCardController < Users::BaseController

	def index
		@active_stamp_cards = StampCard.active_cards.order(id: :desc)
		@old_stamp_cards = StampCard.old_cards.order(id: :desc)
	end

	def detail
		@stamp_card = StampCard.find(params[:stamp_card_id])
	end

	def stamp
		unless /^teshigoto_stamp_card_id=\d$/.match?(params[:qr_decode])
			render json: {message: 'QRコードの解析エラーです。'}, status: :unprocessable_entity
			return
		end
		stamp_card_id = /\d$/.match(params[:qr_decode]).to_s

		stamp_card = StampCard.where(id: stamp_card_id).first
		if stamp_card.blank?
			render json: {message: 'QRコードに紐づくスタンプカードが見つかりません。'}, status: :not_found
			return
		end

		if Time.zone.today < stamp_card.start_at
			render json: {message: "「#{stamp_card.name}」は開催前です。"}, status: :forbidden
			return
		end

		if stamp_card.end_at < Time.zone.today
			render json: {message: "「#{stamp_card.name}」は開催終了しました。"}, status: :forbidden
			return
		end

		if stamp_card.complete?(current_user.id)
			render json: {
					message: '全スタンプ取得済み',
					stamp_card_id: stamp_card_id,
					count: stamp_card.count,
					got_count: stamp_card.got_stamps(current_user.id).count,
					stamp_id: '',
			}, status: :ok
			return
		end

		stamp = Stamp.new
		stamp.user_id = current_user.id
		stamp.stamp_card_id = stamp_card.id
		if stamp.save
			render json: {
					message: 'success',
					stamp_card_id: stamp_card_id,
					count: stamp_card.count,
					got_count: stamp_card.got_stamps(current_user.id).count,
					stamp_id: stamp.id,
			}, status: :ok
		else
			render json: {message: stamp.errors}, status: :unprocessable_entity
		end
	end

	def my_stamps
		stamps = StampCard.find(params[:stamp_card_id]).got_stamps(current_user.id).order(:created_at)
		stamp_array = stamps.map do |stamp|
			{id: stamp.id, date: I18n.l(stamp.created_at.to_date, format: :short)}
		end
		render json: {stamps: stamp_array}, status: :ok
	end
end

app/helpers/managers/managers_helper.rb
module Managers::ManagersHelper
end

app/helpers/managers/stamp_cards_helper.rb
module Managers::StampCardsHelper
end

app/helpers/managers/users_helper.rb
module Managers::UsersHelper
end

app/views/managers/stamp_cards/_form.html.erb
<%= form_with(model: [:managers, stamp_card], local: true, class: 'stampCardForm') do |form| %>
	<% if stamp_card.errors.any? %>
		<div class="cmn-alert">
			<p class="mgt-0 textBold">スタンプカードの保存に失敗しました。</p>

			<ul>
				<% stamp_card.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<dl class="cmn-form mgt-30">
		<dt class="required">スタンプカード名</dt>
		<dd>
			<%= form.text_field :name, required: true %>
		</dd>
	</dl>
	<dl class="cmn-form">
		<dt class="required">説明文章</dt>
		<dd>
			<%= form.text_area :description, required: true %>
		</dd>
	</dl>
	<dl class="cmn-form">
		<dt class="required">スタンプ数</dt>
		<dd>
			<%= form.number_field :count, class: 'is-short', required: true %>
		</dd>
	</dl>
	<dl class="cmn-form">
		<dt class="required">開催期間</dt>
		<dd>
			<%= form.text_field :start_at, class: 'is-short datepicker', required: true %> 〜
			<%= form.text_field :end_at, class: 'is-short datepicker', required: true %>
		</dd>
	</dl>

	<div class="cmn-btnContainer col2 mgt-30">
		<%= form.submit '保存する', class: 'cmn-btn' %>
		<%= link_to 'キャンセル', managers_stamp_cards_path, class: 'cmn-btn' %>
	</div>
<% end %>

app/views/managers/stamp_cards/edit.html.erb
<h1 class="cmn-title">スタンプカード編集</h1>

<%= render 'form', stamp_card: @stamp_card %>

app/views/managers/stamp_cards/index.html.erb
<h1 class="cmn-title">スタンプカード一覧</h1>

<div class="cmn-btnContainer mgt-30">
	<%= link_to '新規作成', new_managers_stamp_card_path, class: 'cmn-btn' %>
</div>

<div class="cmn-tableResponsive">
	<table class="cmn-table mgt-30">
		<thead>
		<tr>
			<th width="80">ID</th>
			<th width="100">状態</th>
			<th>名前</th>
			<th>参加者</th>
			<th width="250">操作</th>
		</tr>
		</thead>

		<tbody>
		<% @stamp_cards.each do |stamp_card| %>
			<tr>
				<td class="alignCenter"><%= stamp_card.id %></td>
				<td class="alignCenter"><%= stamp_card.status_string %></td>
				<td><%= link_to stamp_card.name, [:managers, stamp_card] %></td>
				<td class="alignCenter">10人</td>
				<td class="alignCenter">
					<%= link_to '詳細', [:managers, stamp_card], class: 'cmn-btn is-inline' %>
					<%= link_to '編集', edit_managers_stamp_card_path(stamp_card), class: 'cmn-btn is-inline' %>
					<%= link_to '削除', [:managers, stamp_card], method: :delete, data: {confirm: '本当に削除しますか？'}, class: 'cmn-btn is-inline is-danger' %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/managers/stamp_cards/new.html.erb
<h1 class="cmn-title">スタンプカードの作成</h1>

<%= render 'form', stamp_card: @stamp_card %>

app/views/managers/stamp_cards/show.html.erb
<h1 class="cmn-title">スタンプカード詳細</h1>
<dl class="cmn-form">
	<dt>ID</dt>
	<dd><%= @stamp_card.id %></dd>
</dl>
<dl class="cmn-form">
	<dt>スタンプカード名</dt>
	<dd><%= @stamp_card.name %></dd>
</dl>
<dl class="cmn-form">
	<dt>説明文章</dt>
	<dd><%= @stamp_card.description %></dd>
</dl>
<dl class="cmn-form">
	<dt>スタンプ数</dt>
	<dd><%= @stamp_card.count %></dd>
</dl>
<dl class="cmn-form">
	<dt>開催期間</dt>
	<dd><%= l @stamp_card.start_at %> 〜 <%= l @stamp_card.end_at %></dd>
</dl>
<div class="cmn-btnContainer mgt-30">
	<%= link_to '修正', edit_managers_stamp_card_path(@stamp_card), class: 'cmn-btn' %>
</div>

<h2 class="cmn-title mgt-60">参加者一覧</h2>

<div class="cmn-tableResponsive">
	<table class="cmn-table">
		<thead>
		<tr>
			<th width="50">順位</th>
			<th width="80">ユーザ</th>
			<th width="100">スタンプ数</th>
		</tr>
		</thead>

		<tbody>
		<tr>
			<td class="alignCenter">1</td>
			<td>yamashita-ayuko@s-online.co.jp</td>
			<td class="alignCenter">5 / 10 個</td>
		</tr>
		</tbody>
	</table>
</div>

<div class="cmn-btnContainer mgt-30">
	<%= link_to '戻る', managers_stamp_cards_path, class: 'cmn-btn' %>
</div>