config/routes.rb
Rails.application.routes.draw do

	devise_for :managers, controllers: {
			sessions: 'managers/sessions',
			passwords: 'managers/passwords',
			registrations: 'managers/registrations',
			invitations: 'managers/invitations'
	}

	devise_scope :user do
		authenticated :user do
			root :to => 'users/stamp_card#index', as: :user_authenticated_root
		end
		unauthenticated :user do
			root :to => 'users/sessions#new', as: :user_unauthenticated_root
		end
	end

	devise_for :users, controllers: {
			sessions: 'users/sessions',
			passwords: 'users/passwords',
			registrations: 'users/registrations',
			confirmations: 'users/confirmations'
	}

	namespace :managers do
		get '/', to: 'index#index'
		resources :stamp_cards
		resources :users, :only => [:index, :show]
		resources :managers, :only => [:index, :show, :destroy]
	end

	namespace :users do
		get 'stamp_cards', to: 'stamp_card#index'
		get 'stamp_card/:stamp_card_id', to: 'stamp_card#detail', as: 'stamp_card'
		get 'stamp_card/:stamp_card_id/my_stamps', to: 'stamp_card#my_stamps', as: 'stamp_card_my_stamps'
		post 'stamp_card/stamp', to: 'stamp_card#stamp', as: 'stamp_card_stamp'
	end
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :confirmable,
				 :recoverable, :rememberable, :validatable
end

app/controllers/managers/users_controller.rb
class Managers::UsersController < Managers::BaseController
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
	layout 'users/application'

	before_action :authenticate_user!
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
	layout 'login'

	# GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
	layout 'users/login'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
	layout :resolve_layout

	# before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

	private
	def resolve_layout
		if action_name == 'new' || action_name == 'create'
			'login'
		else
			'application'
		end
	end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
	layout 'login'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/stamp_card_controller.rb
class Users::StampCardController < Users::BaseController

	def index
		@active_stamp_cards = StampCard.active_cards.order(id: :desc)
		@old_stamp_cards = StampCard.old_cards.order(id: :desc)
	end

	def detail
		@stamp_card = StampCard.find(params[:stamp_card_id])
	end

	def stamp
		unless /^teshigoto_stamp_card_id=\d$/.match?(params[:qr_decode])
			render json: {message: 'QRコードの解析エラーです。'}, status: :unprocessable_entity
			return
		end
		stamp_card_id = /\d$/.match(params[:qr_decode]).to_s

		stamp_card = StampCard.where(id: stamp_card_id).first
		if stamp_card.blank?
			render json: {message: 'QRコードに紐づくスタンプカードが見つかりません。'}, status: :not_found
			return
		end

		if Time.zone.today < stamp_card.start_at
			render json: {message: "「#{stamp_card.name}」は開催前です。"}, status: :forbidden
			return
		end

		if stamp_card.end_at < Time.zone.today
			render json: {message: "「#{stamp_card.name}」は開催終了しました。"}, status: :forbidden
			return
		end

		if stamp_card.complete?(current_user.id)
			render json: {
					message: '全スタンプ取得済み',
					stamp_card_id: stamp_card_id,
					count: stamp_card.count,
					got_count: stamp_card.got_stamps(current_user.id).count,
					stamp_id: '',
			}, status: :ok
			return
		end

		stamp = Stamp.new
		stamp.user_id = current_user.id
		stamp.stamp_card_id = stamp_card.id
		if stamp.save
			render json: {
					message: 'success',
					stamp_card_id: stamp_card_id,
					count: stamp_card.count,
					got_count: stamp_card.got_stamps(current_user.id).count,
					stamp_id: stamp.id,
			}, status: :ok
		else
			render json: {message: stamp.errors}, status: :unprocessable_entity
		end
	end

	def my_stamps
		stamps = StampCard.find(params[:stamp_card_id]).got_stamps(current_user.id).order(:created_at)
		stamp_array = stamps.map do |stamp|
			{id: stamp.id, date: I18n.l(stamp.created_at.to_date, format: :short)}
		end
		render json: {stamps: stamp_array}, status: :ok
	end
end

app/helpers/managers/users_helper.rb
module Managers::UsersHelper
end

app/views/layouts/users/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SOL STAMP</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_pack_tag 'application-user', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application-user', 'data-turbolinks-track': 'reload' %>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<body>
<header class="header">
	<h1><a href="/">SOL STAMP</a></h1>
	<div id="nav-drawer">
		<input id="nav-input" type="checkbox" class="nav-unshown">
		<label id="nav-open" for="nav-input"><span></span></label>
		<label class="nav-unshown nav-close-bg" for="nav-input"></label>
		<nav id="nav-content">
			<label class="nav-close" for="nav-input">×</label>
			<ul>
				<li><%= link_to 'スタンプカード', users_stamp_cards_path %></li>
				<li><%= link_to 'アカウント編集', edit_user_registration_path %></li>
				<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
			</ul>
		</nav>
	</div>
</header>
<div class="container">
	<%- if notice.present? %>
		<p class="cmn-notice"><%= notice %></p>
	<%- end %>
	<%- if alert.present? %>
		<p class="cmn-alert"><%= alert %></p>
	<%- end %>
	<%= yield %>
</div>
<%= render 'users/shared/qr_readed_dialog' %>
<footer class="footer">
	<%- if !(controller_name == 'stamp_card' && action_name == 'detail') %>
		<label class="footer_camera" data-camera="true">
			<i class="fas fa-camera"></i>
			<input type="file" accept="image/*" capture="environment" data-camera="true">
			<input type="hidden" data-qr-decord="true">
		</label>
	<%- end %>

	SOL STAMP
</footer>
</body>
</html>

app/views/layouts/users/login.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SOL STAMP</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_pack_tag 'application-user', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application-user', 'data-turbolinks-track': 'reload' %>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<body>
<header class="header">
	<h1><a href="/">SOL STAMP</a></h1>
</header>
<div class="container">
	<%- if notice.present? %>
		<p class="cmn-notice"><%= notice %></p>
	<%- end %>
	<%- if alert.present? %>
		<p class="cmn-alert"><%= alert %></p>
	<%- end %>
	<%= yield %>
</div>
</body>
</html>